# # Calculating FEWSNET Food Consumption Matrix
#
# fews_vars <- c("fcs_cat", "rcsi_cat", "hhs_cat_ipc")
#
# if(length(setdiff(fews_vars, colnames(df)))==0) {
#
#   df <- df %>% dplyr::mutate(fc_cell = ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "None" & .data$rcsi_cat == "No to Low", 1,
#                                               ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "Little" & .data$rcsi_cat == "No to Low", 2,
#                                                      ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "Moderate" & .data$rcsi_cat == "No to Low", 3,
#                                                             ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "Severe" & .data$rcsi_cat == "No to Low", 4,
#                                                                    ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "Very Severe" & .data$rcsi_cat == "No to Low", 5,
#                                                                           ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "None" & .data$rcsi_cat == "No to Low", 6,
#                                                                                  ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "Little" & .data$rcsi_cat == "No to Low", 7,
#                                                                                         ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "Moderate" & .data$rcsi_cat == "No to Low", 8,
#                                                                                                ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "Severe" & .data$rcsi_cat == "No to Low", 9,
#                                                                                                       ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "Very Severe" & .data$rcsi_cat == "No to Low", 10,
#                                                                                                              ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "None" & .data$rcsi_cat == "No to Low", 11,
#                                                                                                                     ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "Little" & .data$rcsi_cat == "No to Low", 12,
#                                                                                                                            ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "Moderate" & .data$rcsi_cat == "No to Low", 13,
#                                                                                                                                   ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "Severe" & .data$rcsi_cat == "No to Low", 14,
#                                                                                                                                          ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "Very Severe" & .data$rcsi_cat == "No to Low", 15,
#                                                                                                                                                 ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "None" & .data$rcsi_cat == "Medium", 16,
#                                                                                                                                                        ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "Little" & .data$rcsi_cat == "Medium", 17,
#                                                                                                                                                               ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "Moderate" & .data$rcsi_cat == "Medium", 18,
#                                                                                                                                                                      ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "Severe" & .data$rcsi_cat == "Medium", 19,
#                                                                                                                                                                             ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "Very Severe" & .data$rcsi_cat == "Medium", 20,
#                                                                                                                                                                                    ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "None" & .data$rcsi_cat == "Medium", 21,
#                                                                                                                                                                                           ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "Little" & .data$rcsi_cat == "Medium", 22,
#                                                                                                                                                                                                  ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "Moderate" & .data$rcsi_cat == "Medium", 23,
#                                                                                                                                                                                                         ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "Severe" & .data$rcsi_cat == "Medium", 24,
#                                                                                                                                                                                                                ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "Very Severe" & .data$rcsi_cat == "Medium", 25,
#                                                                                                                                                                                                                       ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "None" & .data$rcsi_cat == "Medium", 26,
#                                                                                                                                                                                                                              ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "Little" & .data$rcsi_cat == "Medium", 27,
#                                                                                                                                                                                                                                     ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "Moderate" & .data$rcsi_cat == "Medium", 28,
#                                                                                                                                                                                                                                            ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "Severe" & .data$rcsi_cat == "Medium", 29,
#                                                                                                                                                                                                                                                   ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "Very Severe" & .data$rcsi_cat == "Medium", 30,
#                                                                                                                                                                                                                                                          ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "None" & .data$rcsi_cat == "High", 31,
#                                                                                                                                                                                                                                                                 ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "Little" & .data$rcsi_cat == "High", 32,
#                                                                                                                                                                                                                                                                        ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "Moderate" & .data$rcsi_cat == "High", 33,
#                                                                                                                                                                                                                                                                               ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "Severe" & .data$rcsi_cat == "High", 34,
#                                                                                                                                                                                                                                                                                      ifelse(.data$fcs_cat == "Acceptable" & .data$hhs_cat_ipc == "Very Severe" & .data$rcsi_cat == "High", 35,
#                                                                                                                                                                                                                                                                                             ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "None" & .data$rcsi_cat == "High", 36,
#                                                                                                                                                                                                                                                                                                    ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "Little" & .data$rcsi_cat == "High", 37,
#                                                                                                                                                                                                                                                                                                           ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "Moderate" & .data$rcsi_cat == "High", 38,
#                                                                                                                                                                                                                                                                                                                  ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "Severe" & .data$rcsi_cat == "High", 39,
#                                                                                                                                                                                                                                                                                                                         ifelse(.data$fcs_cat == "Borderline" & .data$hhs_cat_ipc == "Very Severe" & .data$rcsi_cat == "High", 40,
#                                                                                                                                                                                                                                                                                                                                ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "None" & .data$rcsi_cat == "High", 41,
#                                                                                                                                                                                                                                                                                                                                       ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "Little" & .data$rcsi_cat == "High", 42,
#                                                                                                                                                                                                                                                                                                                                              ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "Moderate" & .data$rcsi_cat == "High", 43,
#                                                                                                                                                                                                                                                                                                                                                     ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "Severe" & .data$rcsi_cat == "High", 44,
#                                                                                                                                                                                                                                                                                                                                                            ifelse(.data$fcs_cat == "Poor" & .data$hhs_cat_ipc == "Very Severe" & .data$rcsi_cat == "High", 45, NA))))))))))))))))))))))))))))))))))))))))))))))
#
#   df <- df %>% dplyr::mutate(fc_phase = ifelse(.data$fc_cell == 1 | .data$fc_cell == 6, "Phase 1 FC",
#                                                ifelse(.data$fc_cell == 2 |.data$fc_cell == 3|.data$fc_cell == 7|.data$fc_cell == 11|.data$fc_cell == 12|.data$fc_cell == 16|.data$fc_cell == 17|.data$fc_cell == 18|.data$fc_cell == 21|.data$fc_cell == 22|.data$fc_cell == 26|.data$fc_cell == 31|.data$fc_cell == 32|.data$fc_cell == 36, "Phase 2 FC",
#                                                       ifelse(.data$fc_cell == 4|.data$fc_cell == 5|.data$fc_cell == 8|.data$fc_cell == 9|.data$fc_cell == 13|.data$fc_cell == 19|.data$fc_cell == 20|.data$fc_cell == 23|.data$fc_cell == 24|.data$fc_cell == 27|.data$fc_cell == 28|.data$fc_cell == 33|.data$fc_cell == 34|.data$fc_cell == 37|.data$fc_cell == 38|.data$fc_cell == 41|.data$fc_cell == 42|.data$fc_cell == 43,"Phase 3 FC",
#                                                              ifelse(.data$fc_cell == 10|.data$fc_cell == 14|.data$fc_cell == 15|.data$fc_cell == 25|.data$fc_cell == 29|.data$fc_cell == 35|.data$fc_cell == 39|.data$fc_cell == 40|.data$fc_cell == 44, "Phase 4 FC",
#                                                                     ifelse(.data$fc_cell == 30 | .data$fc_cell == 45, "Phase 5 FC", NA))))))
#
# }
